# Generated by Django 5.0.6 on 2024-06-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('familiar_cargo', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=50)),
                ('situacion_salud', models.CharField(max_length=25)),
                ('cuidados_especiales', models.TextField()),
            ],
        ),
    ]
